[package]
name = "painel_controller"
version = "0.1.0"
edition = "2021"

[lib]
name = "painel_controller"
path = "src/lib.rs"
crate-type = ["rlib"]


[dependencies]
sql_lite = {path = "../../common/sql_lite" }
